name: iotflutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hsvcolor_picker: ^1.5.0
  http: ^1.1.0
  intl: ^0.19.0
  mqtt5_client: ^4.0.4
  uuid: ^4.2.2
  go_router: ^13.1.0
  sliding_clipped_nav_bar: ^3.1.0+4
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/credentials/AmazonRootCA1.pem
    # - assets/credentials/Private.pem.key
    # - assets/credentials/Certificate.pem.crt
    - assets/AmazonRootCA1.pem
    - assets/Private.pem.key
    - assets/Certificate.pem.crt
